### ISSUE TITLE
Wrong variable substitution in vvv-init.sh

### ISSUE THREAD

**Issue by chrean** [Automattic/vvv-vip-go#6]
I think there is a problem with vvv-init.sh.

In nginx.conf template for custom site there is this line:

https://github.com/Automattic/vvv-vip-go/blob/fa9a8e1f125c1e505a16a51f257a66e381e7cdde/provision/vvv-nginx.conf.tmpl#L4

However, in `vvv-init.sh` the substitution is attempted on a different variable name:

https://github.com/Automattic/vvv-vip-go/blob/fa9a8e1f125c1e505a16a51f257a66e381e7cdde/provision/vvv-init.sh#L121

So my guess is, variable name should be changed in either file.

Note: I have tried to make the change into vvv-init-sh and it worked. I can submit the code if you want me to.

**Comment by tomjn** [comment]
Thanks for the heads up!
